lite_deploy_1.1

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -49,9 +49,11 @@ jobs:
             exit 1
           fi
           export KUBECONFIG=$PWD/kubeconfig
+          kubectl config current-context || (echo "ERROR: current-context not set - fix your secret YAML"; exit 1)
 
       - name: Deploy to Kubernetes
         run: |
+          export KUBECONFIG=$PWD/kubeconfig
           kubectl set image deployment/myapp myapp=ghcr.io/${{ github.repository_owner }}/tts_ci_git/myapp:${{ github.sha }} -n default
           kubectl rollout status deployment/myapp -n default --timeout=300s
 
